apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  labels:
    project: selfservice
    department: devex
    app: tika
    component: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
        project: selfservice
        department: devex
    spec:
      containers:
      - name: tika
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/tika:361804
        ports:
        - containerPort: 3000
          name: web
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
