apiVersion: v1
kind: Service
metadata:
  name: tika
  labels:
    app: tika
    project: selfservice
    department: devex    
    component: tika
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    app: tika
